### ISSUE TITLE
tfs unlock no longer works on VS 2017

### ISSUE THREAD

**Issue by tribicito** [danactive/tfs-unlock#14]
Microsoft changed the path for TF.exe in Visual Studio 2017. As a result, gulp is no longer able to checkout the file when it tries to use the EXE. The issue happens when the machine only has VS 2017 installed. For example if the machine has VS 2015 and VS 2017 installed, it will work because it will find the exe in the VS 2015 folder.

**Comment by tribicito** [comment]
#16 I created a pull request that fixes this issue.

**Comment by danactive** [comment]
@tribicito Thanks for your appropriate pull request, I published this as version 0.6.0 to npm
