### ISSUE TITLE
Not working for VS2017 Enterprise

### ISSUE THREAD

**Issue by brown0617** [danactive/tfs-unlock#18]
The vs2017 path is set to:

vs2017: {
        "bit32": 'C:\\Program Files\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer\\',
        "bit64": 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer\\'
	}

This is a problem for Enterprise installations where the folder name is "Enterprise" rather than "Professional".

**Comment by danactive** [comment]
Hi @brown0617 looking at the documentation you should be able to pass in a custom path for Enterprise

```
const tfs = require('tfs-unlock');

tfs.init({
	visualStudioPath: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\'
});
```

**Comment by Wolvenstone** [comment]
Added support for Community and Enterprise Visual Studio versions out of the box. Some other projects using tfs-unlock do not allow passing the visualStudioPath setting, so I think this is the easiest solution for all.

#23
