### ISSUE TITLE
Add the "add" functionality

### ISSUE THREAD

**Issue by rpannell** [danactive/tfs-unlock#19]
exports.add = function (paths) {
	return tfs(paths, 'add');
};

this would be a huge help!  Tested it locally and works (2017 pro)

**Comment by danactive** [comment]
What problem are you trying to solve?

**Comment by rpannell** [comment]
adding a newly created file to TFS

Checkout will only check out currently created file, but if you create a file and want to add it to TFS then the add command must be called.

**Comment by danactive** [comment]
Will you create a pull request with this new feature? I'm no longer on Windows so I'm unable to verify

**Comment by rpannell** [comment]
Yep no problem.  Will probably take a few days before I have the time to do the full gambit.  I will only be able to test on VS2017Pro, but I don't think that should change much between the others
